name: test

on: [pull_request, push]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      
      - name: Run tox -e lint
        run: tox
        env:
          TOXENV: lint
  
  test:
    name: unittests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toxenv:
            - py36-dj22-wag29
            - py36-dj22-waglatest
            - py38-dj22-wag29
            - py38-dj22-waglatest
            - py38-dj31-waglatest
        include:
          - toxenv: py36-dj22-wag29
            python-version: 3.6
          - toxenv: py36-dj22-waglatest
            python-version: 3.6
          - toxenv: py38-dj22-wag29
            python-version: 3.8
          - toxenv: py38-dj22-waglatest
            python-version: 3.8
          - toxenv: py38-dj31-waglatest
            python-version: 3.8
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tox
        run: |
            tox
        env: 
          TOXENV: ${{ matrix.toxenv }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
